# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      service1:
        image: mail2prajwal12/node-express-rest-api:latest
        ports:
          - 3000:3000
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3  
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven
    - name: Test the docker image
      run: curl --location --request GET 'localhost:3000/calculator/subtraction?num1=4&num2=2'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Deploy cucumber report to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./reports/
