# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3  
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Use node-express-rest-api:latest docker image
      uses: docker://mail2prajwal12/node-express-rest-api:latest
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Deploy cucumber report to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./reports/
